[DDCE-4525] Dependency Update + cleanup
hmrc/ers-file-validator pull request #56
Opened 2023-08-16 14:18 UTC by matthewwardcap

# DDCE-4525

Dependency update + fix various warnings

 - [X]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [X]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [X]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [X]  I've squashed my commits - including the JIRA issue number in the commit message
 - [X]  I've run a dependency check to ensure all dependencies are up to date

2023-08-16 14:38 UTC, matthewwardcap commented
> * There is a bobby warning - see the pr builder for details
> * There is a bobby error - see the pr builder for details

Bobby error has been fixed, bobby warn about `http-caching-client` only applies currently to new projects, no migration

2023-08-22 14:53 UTC, frikit requested changes

2023-08-22 14:53 UTC, frikit commented on build.sbt
>      ScoverageKeys.coverageFailOnMinimum := false,
set it to true

2023-08-22 14:58 UTC, matthewwardcap commented on build.sbt
>      ScoverageKeys.coverageFailOnMinimum := false,
Done

2023-08-22 16:47 UTC, frikit approved these changes

2023-08-22 18:34 UTC, merged